# Generated by Django 5.0.2 on 2025-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
